apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: demo
  labels:
    app: go-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: pkbhowmick/agent-load-test:v0.0.3
        imagePullPolicy: IfNotPresent
        env:
        - name: X-OPTIMIZELY-SDK-KEY
          value: ""
        - name: DECIDE_URL
          value: ""
